"""setupEM GUI integration and an importable Driven-model script."""

from __future__ import annotations

from pathlib import Path
import shutil
import subprocess

from .em import EigenmodeParameters, MeshParameters
from .errors import ExternalToolError


def setupem_argv(
    gds_path: str | Path,
    stackup_path: str | Path,
    *,
    executable: str = "setupEM",
) -> list[str]:
    return [
        executable,
        "-gdsfile",
        str(Path(gds_path)),
        "-xmlfile",
        str(Path(stackup_path)),
    ]


def launch_setupem(
    gds_path: str | Path,
    stackup_path: str | Path,
    *,
    executable: str = "setupEM",
) -> subprocess.Popen[str]:
    resolved = shutil.which(executable)
    if resolved is None and not Path(executable).is_file():
        raise ExternalToolError(
            "setupEM was not found. Install with `pip install -e '.[gui]'`."
        )
    return subprocess.Popen(
        setupem_argv(gds_path, stackup_path, executable=resolved or executable),
        text=True,
    )


def setupem_model_source(
    *,
    gds_filename: str,
    stackup_filename: str,
    mesh: MeshParameters,
    eigenmode: EigenmodeParameters,
    model_name: str = "geerlings_fig1_driven",
    left_port_layer: int = 201,
    right_port_layer: int = 202,
    metal_datatype: int = 0,
    port_datatype: int = 0,
) -> str:
    """Return executable gds2palace code that setupEM can also import.

    The configurable left/right marker layers (201/202 by default) are
    transverse sheets at the CPW ends. They are mapped to Nb as two 50-ohm
    in-plane ports for an S21 notch cross-check. This is separate from the
    port-free Eigenmode configuration.
    """

    mesh.validate()
    eigenmode.validate()
    boundary = mesh.boundary.upper()
    return f'''# Generated by geerlings-em; executable and importable by setupEM.
import os
import sys
import subprocess
from gds2palace import gds_reader, simulation_setup, stackup_reader, utilities

gds_filename = {gds_filename!r}
XML_filename = {stackup_filename!r}
unit = 1e-6
purpose = {metal_datatype!r}
preprocess_gds = {mesh.preprocess_gds!r}
merge_polygon_size = 0
margin = {mesh.dielectric_margin_um!r}
air_around = [{mesh.air_margin_xy_um!r}, {mesh.air_margin_xy_um!r},
              {mesh.air_margin_xy_um!r}, {mesh.air_margin_xy_um!r},
              {mesh.air_below_um!r}, {mesh.air_above_um!r}]
boundary = [{boundary!r}] * 6
fstart = {eigenmode.target_frequency_ghz * 1e9!r}
fstop = {eigenmode.search_max_frequency_ghz * 1e9!r}
fstep = 10e6
refined_cellsize = {mesh.refined_cell_size_um!r}
cells_per_wavelength = {mesh.cells_per_wavelength!r}
meshsize_max = {mesh.max_cell_size_um!r}
adaptive_mesh_iterations = {mesh.adaptive_iterations!r}
order = {eigenmode.order!r}

script_path = utilities.get_script_path(__file__)
model_basename = {model_name!r}
sim_path = utilities.create_sim_path(script_path, model_basename)
os.chdir(os.path.dirname(os.path.abspath(__file__)))

settings = {{
    "unit": unit,
    "margin": margin,
    "air_around": air_around,
    "boundary": boundary,
    "fstart": fstart,
    "fstop": fstop,
    "fstep": fstep,
    "refined_cellsize": refined_cellsize,
    "cells_per_wavelength": cells_per_wavelength,
    "meshsize_max": meshsize_max,
    "adaptive_mesh_iterations": adaptive_mesh_iterations,
    "order": order,
    "nogui": ("nogui" in sys.argv),
}}

simulation_ports = simulation_setup.all_simulation_ports()
simulation_ports.add_port(simulation_setup.simulation_port(portnumber=1, voltage=1, port_Z0=50, source_layernum={left_port_layer!r}, target_layername="Nb", direction="+y"))
simulation_ports.add_port(simulation_setup.simulation_port(portnumber=2, voltage=1, port_Z0=50, source_layernum={right_port_layer!r}, target_layername="Nb", direction="+y"))

materials_list, dielectrics_list, metals_list = stackup_reader.read_substrate(XML_filename)
layernumbers = metals_list.getlayernumbers()
layernumbers.extend(simulation_ports.portlayers)
allpolygons = gds_reader.read_gds(
    gds_filename, layernumbers,
    purposelist={list(dict.fromkeys((metal_datatype, port_datatype)))!r},
    metals_list=metals_list,
    preprocess=preprocess_gds, merge_polygon_size=merge_polygon_size)

settings.update({{
    "simulation_ports": simulation_ports,
    "materials_list": materials_list,
    "dielectrics_list": dielectrics_list,
    "metals_list": metals_list,
    "layernumbers": layernumbers,
    "allpolygons": allpolygons,
    "sim_path": sim_path,
    "model_basename": model_basename,
}})
excite_ports = simulation_ports.all_active_excitations()
simulation_setup.create_palace(excite_ports, settings)
utilities.create_run_script(sim_path)
'''


def write_setupem_model(
    path: str | Path,
    *,
    gds_filename: str,
    stackup_filename: str,
    mesh: MeshParameters,
    eigenmode: EigenmodeParameters,
    model_name: str = "geerlings_fig1_driven",
    left_port_layer: int = 201,
    right_port_layer: int = 202,
    metal_datatype: int = 0,
    port_datatype: int = 0,
) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        setupem_model_source(
            gds_filename=gds_filename,
            stackup_filename=stackup_filename,
            mesh=mesh,
            eigenmode=eigenmode,
            model_name=model_name,
            left_port_layer=left_port_layer,
            right_port_layer=right_port_layer,
            metal_datatype=metal_datatype,
            port_datatype=port_datatype,
        ),
        encoding="utf-8",
    )
    return target
